:sparkles::lock: add github action scanning
scality/sbom pull request #8
Opened 2024-03-29 19:28 UTC by m4nch0t

Add support for github actions sbom

2024-03-29 22:40 UTC, tcarmet requested changes
One comment requiring some attention, the rest LGTM

2024-03-29 22:40 UTC, tcarmet commented on tests/.github/workflows/install-python.yaml
This seems like an unrelated file that was committed. Or if it's not unrelated, the runner do not exist and will not be picked up.

2024-04-04 14:24 UTC, m4nch0t commented on tests/.github/workflows/install-python.yaml
It's only a test file for sbom generation. To check if scan are running well.

2024-04-04 16:34 UTC, tcarmet approved these changes

2024-04-04 16:34 UTC, tcarmet commented on tests/.github/workflows/install-python.yaml
ok ok, my bad then.

2024-04-04 18:56 UTC, merged